

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class Labs : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Labs entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Labs()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Labs(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Labs> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Labs.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Labs_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Labs_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Labs.DetailsClass.GetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.Labs.DetailsClass.SetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ViralLoad
        {
            get
            {
                return global::LightSwitchApplication.Labs.DetailsClass.GetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.ViralLoad);
            }
            set
            {
                global::LightSwitchApplication.Labs.DetailsClass.SetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.ViralLoad, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ViralLoad_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ViralLoad_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ViralLoad_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LabDate
        {
            get
            {
                return global::LightSwitchApplication.Labs.DetailsClass.GetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.LabDate);
            }
            set
            {
                global::LightSwitchApplication.Labs.DetailsClass.SetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.LabDate, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabDate_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabDate_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabDate_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Patient Patient
        {
            get
            {
                return global::LightSwitchApplication.Labs.DetailsClass.GetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Patient);
            }
            set
            {
                global::LightSwitchApplication.Labs.DetailsClass.SetValue(this, global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Patient, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patient_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patient_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patient_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Labs,
                global::LightSwitchApplication.Labs.DetailsClass,
                global::LightSwitchApplication.Labs.DetailsClass.IImplementation,
                global::LightSwitchApplication.Labs.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass>.Entry
                __LabsEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass>.Entry(
                    global::LightSwitchApplication.Labs.DetailsClass.__Labs_CreateNew,
                    global::LightSwitchApplication.Labs.DetailsClass.__Labs_Created,
                    global::LightSwitchApplication.Labs.DetailsClass.__Labs_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Labs __Labs_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Labs> es)
            {
                return new global::LightSwitchApplication.Labs(es);
            }
            private static void __Labs_Created(global::LightSwitchApplication.Labs e)
            {
                e.Labs_Created();
            }
            private static bool __Labs_AllowSaveWithErrors(global::LightSwitchApplication.Labs e)
            {
                bool result = false;
                e.Labs_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Labs.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int> ViralLoad
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.ViralLoad) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.DateTime> LabDate
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.LabDate) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::LightSwitchApplication.Patient> Patient
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Patient) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::LightSwitchApplication.Patient>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new int ViralLoad { get; set; }
                new global::System.DateTime LabDate { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Patient { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Labs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>.Data> c, global::LightSwitchApplication.Labs.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Labs e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Labs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Labs e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>.Entry
                    ViralLoad = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>.Entry(
                        "ViralLoad",
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._ViralLoad_Stub,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._ViralLoad_ComputeIsReadOnly,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._ViralLoad_Validate,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._ViralLoad_GetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._ViralLoad_SetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._ViralLoad_OnValueChanged);
                private static void _ViralLoad_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Labs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>.Data> c, global::LightSwitchApplication.Labs.DetailsClass d, object sf)
                {
                    c(d, ref d._ViralLoad, sf);
                }
                private static bool _ViralLoad_ComputeIsReadOnly(global::LightSwitchApplication.Labs e)
                {
                    bool result = false;
                    e.ViralLoad_IsReadOnly(ref result);
                    return result;
                }
                private static void _ViralLoad_Validate(global::LightSwitchApplication.Labs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ViralLoad_Validate(r);
                }
                private static int _ViralLoad_GetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    return d.ImplementationEntity.ViralLoad;
                }
                private static void _ViralLoad_SetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d, int v)
                {
                    d.ImplementationEntity.ViralLoad = v;
                }
                private static void _ViralLoad_OnValueChanged(global::LightSwitchApplication.Labs e)
                {
                    e.ViralLoad_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.DateTime>.Entry
                    LabDate = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.DateTime>.Entry(
                        "LabDate",
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._LabDate_Stub,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._LabDate_ComputeIsReadOnly,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._LabDate_Validate,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._LabDate_GetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._LabDate_SetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._LabDate_OnValueChanged);
                private static void _LabDate_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Labs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Labs.DetailsClass d, object sf)
                {
                    c(d, ref d._LabDate, sf);
                }
                private static bool _LabDate_ComputeIsReadOnly(global::LightSwitchApplication.Labs e)
                {
                    bool result = false;
                    e.LabDate_IsReadOnly(ref result);
                    return result;
                }
                private static void _LabDate_Validate(global::LightSwitchApplication.Labs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LabDate_Validate(r);
                }
                private static global::System.DateTime _LabDate_GetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    return d.ImplementationEntity.LabDate;
                }
                private static void _LabDate_SetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.LabDate = global::LightSwitchApplication.Labs.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _LabDate_OnValueChanged(global::LightSwitchApplication.Labs e)
                {
                    e.LabDate_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::LightSwitchApplication.Patient>.Entry
                    Patient = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::LightSwitchApplication.Patient>.Entry(
                        "Patient",
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Patient_Stub,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Patient_ComputeIsReadOnly,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Patient_Validate,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Patient_GetCoreImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Patient_GetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Patient_SetImplementationValue,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Patient_Refresh,
                        global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties._Patient_OnValueChanged);
                private static void _Patient_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Labs.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::LightSwitchApplication.Patient>.Data> c, global::LightSwitchApplication.Labs.DetailsClass d, object sf)
                {
                    c(d, ref d._Patient, sf);
                }
                private static bool _Patient_ComputeIsReadOnly(global::LightSwitchApplication.Labs e)
                {
                    bool result = false;
                    e.Patient_IsReadOnly(ref result);
                    return result;
                }
                private static void _Patient_Validate(global::LightSwitchApplication.Labs e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Patient_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Patient_GetCoreImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    return d.ImplementationEntity.Patient;
                }
                private static global::LightSwitchApplication.Patient _Patient_GetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Patient, global::LightSwitchApplication.Patient.DetailsClass>(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Patient, ref d._Patient);
                }
                private static void _Patient_SetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass d, global::LightSwitchApplication.Patient v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Patient, ref d._Patient, (i, ev) => i.Patient = ev, v);
                }
                private static void _Patient_Refresh(global::LightSwitchApplication.Labs.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Labs.DetailsClass.PropertySetProperties.Patient, ref d._Patient);
                }
                private static void _Patient_OnValueChanged(global::LightSwitchApplication.Labs e)
                {
                    e.Patient_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, int>.Data _ViralLoad;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::System.DateTime>.Data _LabDate;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Labs, global::LightSwitchApplication.Labs.DetailsClass, global::LightSwitchApplication.Patient>.Data _Patient;
            
        }
    
        #endregion
    }
    
    #endregion
}
