//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class EditablePatientsGrid
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.EditablePatientsGrid, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private EditablePatientsGrid() : base("LightSwitchApplication:EditablePatientsGrid")
        {
            global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static EditablePatientsGrid CreateInstance()
        {
            return new global::LightSwitchApplication.EditablePatientsGrid(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePatientsGrid_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePatientsGrid_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePatientsGrid_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePatientsGrid_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePatientsGrid_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePatientsGrid_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void EditablePatientsGrid_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Patients_SelectionChanged();

        partial void Patients_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Patients visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Patient> Patients
        {
            get
            {
                return global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.GetValue(this, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.PropertySetProperties.Patients);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditablePatientsGrid, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.PropertySet, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.CommandSet, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.PropertySetProperties.Patients;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditablePatientsGrid, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass>.Entry
                __EditablePatientsGridEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.EditablePatientsGrid, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass>.Entry(
                    global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.__EditablePatientsGrid_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.__EditablePatientsGrid_InvokeSavingEvent,
                    global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.__EditablePatientsGrid_InvokeSavedEvent,
                    global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.__EditablePatientsGrid_InvokeClosingEvent,
                    global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.__EditablePatientsGrid_InvokeCreated,
                    global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.__EditablePatientsGrid_InvokeActivated,
                    global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.__EditablePatientsGrid_InvokeSaveErrorEvent);
            private static void __EditablePatientsGrid_InvokeInitializeDataWorkspace(global::LightSwitchApplication.EditablePatientsGrid s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.EditablePatientsGrid_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __EditablePatientsGrid_InvokeSavingEvent(global::LightSwitchApplication.EditablePatientsGrid s)
            {
                bool handled = false;
                s.EditablePatientsGrid_Saving(ref handled);
                return handled;
            }
            private static void __EditablePatientsGrid_InvokeSavedEvent(global::LightSwitchApplication.EditablePatientsGrid s)
            {
                s.EditablePatientsGrid_Saved();
            }
            private static bool __EditablePatientsGrid_InvokeClosingEvent(global::LightSwitchApplication.EditablePatientsGrid s)
            {
                bool cancel = false;
                s.EditablePatientsGrid_Closing(ref cancel);
                return cancel;
            }
            private static void __EditablePatientsGrid_InvokeCreated(global::LightSwitchApplication.EditablePatientsGrid s)
            {
                s.EditablePatientsGrid_Created();
            }
            private static void __EditablePatientsGrid_InvokeActivated(global::LightSwitchApplication.EditablePatientsGrid s)
            {
                s.EditablePatientsGrid_Activated();
            }
            private static bool __EditablePatientsGrid_InvokeSaveErrorEvent(global::LightSwitchApplication.EditablePatientsGrid s, global::System.Exception ex)
            {
                bool handled = false;
                s.EditablePatientsGrid_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable PatientsQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Patients;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditablePatientsGrid, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass, global::LightSwitchApplication.Patient>.Data _Patients;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.EditablePatientsGrid, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditablePatientsGrid, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass, global::LightSwitchApplication.Patient> Patients
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditablePatientsGrid, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass, global::LightSwitchApplication.Patient>)base.GetItem(global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.PropertySetProperties.Patients);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.EditablePatientsGrid, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.EditablePatientsGrid, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditablePatientsGrid, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass, global::LightSwitchApplication.Patient>.Entry
                    Patients = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditablePatientsGrid, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass, global::LightSwitchApplication.Patient>.Entry(
                        "Patients",
                        global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.PropertySetProperties._Patients_Stub,
                        global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.PropertySetProperties._Patients_Validate,
                        global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.PropertySetProperties._Patients_CreateQuery,
                        global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.PropertySetProperties._Patients_SelectionChanged,
                        global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.PropertySetProperties._Patients_OnCollectionChanged,
                        global::LightSwitchApplication.EditablePatientsGrid.DetailsClass.PropertySetProperties._Patients_OnLoaded);
                private static void _Patients_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.EditablePatientsGrid.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.EditablePatientsGrid, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass, global::LightSwitchApplication.Patient>.Data> c, global::LightSwitchApplication.EditablePatientsGrid.DetailsClass d, object sf)
                {
                    c(d, ref d._Patients, sf);
                }
                private static void _Patients_Validate(global::LightSwitchApplication.EditablePatientsGrid s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Patients_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Patients_CreateQuery(global::LightSwitchApplication.EditablePatientsGrid.DetailsClass d, object[] args)
                {
                    return d.PatientsQuery();
                }
                private static void _Patients_SelectionChanged(global::LightSwitchApplication.EditablePatientsGrid s)
                {
                    s.Patients_SelectionChanged();
                }
                private static void _Patients_OnCollectionChanged(global::LightSwitchApplication.EditablePatientsGrid s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Patients_Changed(e);
                }
                private static void _Patients_OnLoaded(global::LightSwitchApplication.EditablePatientsGrid s, bool succeeded)
                {
                    s.Patients_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class PatientDetail
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private PatientDetail(int PatientId) : base("LightSwitchApplication:PatientDetail")
        {
                this.PatientId = PatientId;
            global::LightSwitchApplication.PatientDetail.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static PatientDetail CreateInstance(int PatientId)
        {
            return new global::LightSwitchApplication.PatientDetail(
                        PatientId
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientDetail_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Patient_Changed();

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patient_Loaded(bool succeeded);

        partial void PatientId_Changed();

        partial void LabsCollection_SelectionChanged();

        partial void LabsCollection_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsCollection_Loaded(bool succeeded);

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Patient Patient
        {
            get
            {
                return global::LightSwitchApplication.PatientDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.Patient);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patient_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int PatientId
        {
            get 
            {
                return global::LightSwitchApplication.PatientDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.PatientId);
            }
            set
            {
                global::LightSwitchApplication.PatientDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.PatientId, value);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PatientId_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        /// <summary>
        /// Gets the LabsCollection visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Labs> LabsCollection
        {
            get
            {
                return global::LightSwitchApplication.PatientDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.LabsCollection);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsCollection_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySet, global::LightSwitchApplication.PatientDetail.DetailsClass.CommandSet, global::LightSwitchApplication.PatientDetail.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.Patient;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass>.Entry
                __PatientDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeSavingEvent,
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeSavedEvent,
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeClosingEvent,
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeCreated,
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeActivated,
                    global::LightSwitchApplication.PatientDetail.DetailsClass.__PatientDetail_InvokeSaveErrorEvent);
            private static void __PatientDetail_InvokeInitializeDataWorkspace(global::LightSwitchApplication.PatientDetail s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.PatientDetail_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __PatientDetail_InvokeSavingEvent(global::LightSwitchApplication.PatientDetail s)
            {
                bool handled = false;
                s.PatientDetail_Saving(ref handled);
                return handled;
            }
            private static void __PatientDetail_InvokeSavedEvent(global::LightSwitchApplication.PatientDetail s)
            {
                s.PatientDetail_Saved();
            }
            private static bool __PatientDetail_InvokeClosingEvent(global::LightSwitchApplication.PatientDetail s)
            {
                bool cancel = false;
                s.PatientDetail_Closing(ref cancel);
                return cancel;
            }
            private static void __PatientDetail_InvokeCreated(global::LightSwitchApplication.PatientDetail s)
            {
                s.PatientDetail_Created();
            }
            private static void __PatientDetail_InvokeActivated(global::LightSwitchApplication.PatientDetail s)
            {
                s.PatientDetail_Activated();
            }
            private static bool __PatientDetail_InvokeSaveErrorEvent(global::LightSwitchApplication.PatientDetail s, global::System.Exception ex)
            {
                bool handled = false;
                s.PatientDetail_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.PatientDetail.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.PatientDetail.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable LabsCollectionQuery()
            {
                if (this.Screen.Patient == null)
                {
                    return null;
                }

                global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Labs> loader =
                    (global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Labs>)((global::Microsoft.LightSwitch.Details.ILoadableProperty)this.Screen.Patient.Details.Properties.LabsCollection).Loader;
                if (loader == null)
                {
                    return null;
                }

                return loader;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Patient>.Data _Patient;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, int>.Data _PatientId;

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Labs>.Data _LabsCollection;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Patient> Patient
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Patient>)base.GetItem(global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.Patient);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, int> PatientId
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, int>)base.GetItem(global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.PatientId);
                    }
                }

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Labs> LabsCollection
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Labs>)base.GetItem(global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties.LabsCollection);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Patient>.Entry
                    Patient = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Patient>.Entry(
                        "Patient",
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Patient_Stub,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Patient_Validate,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Patient_CreateQuery,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Patient_OnValueChanged,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._Patient_OnLoaded);
                private static void _Patient_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PatientDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenReferenceProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Patient>.Data> c, global::LightSwitchApplication.PatientDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Patient, sf);
                }
                private static void _Patient_Validate(global::LightSwitchApplication.PatientDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Patient_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Patient_CreateQuery(global::LightSwitchApplication.PatientDetail.DetailsClass d, object[] args)
                {
                    return null;
                }
                private static void _Patient_OnValueChanged(global::LightSwitchApplication.PatientDetail s)
                {
                    s.Patient_Changed();
                }

                private static void _Patient_OnLoaded(global::LightSwitchApplication.PatientDetail s, bool succeeded)
                {
                    s.Patient_Loaded(succeeded);
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, int>.Entry
                    PatientId = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, int>.Entry(
                        "PatientId",
                        false,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._PatientId_Stub,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._PatientId_Validate,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._PatientId_OnValueChanged);
                private static void _PatientId_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PatientDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenLocalProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, int>.Data> c, global::LightSwitchApplication.PatientDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._PatientId, sf);
                }
                private static void _PatientId_Validate(global::LightSwitchApplication.PatientDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.PatientId_Validate(r);
                }
                private static void _PatientId_OnValueChanged(global::LightSwitchApplication.PatientDetail s)
                {
                    s.PatientId_Changed();
                }

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Labs>.Entry
                    LabsCollection = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Labs>.Entry(
                        "LabsCollection",
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._LabsCollection_Stub,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._LabsCollection_Validate,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._LabsCollection_CreateQuery,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._LabsCollection_SelectionChanged,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._LabsCollection_OnCollectionChanged,
                        global::LightSwitchApplication.PatientDetail.DetailsClass.PropertySetProperties._LabsCollection_OnLoaded);
                private static void _LabsCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PatientDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.PatientDetail, global::LightSwitchApplication.PatientDetail.DetailsClass, global::LightSwitchApplication.Labs>.Data> c, global::LightSwitchApplication.PatientDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._LabsCollection, sf);
                }
                private static void _LabsCollection_Validate(global::LightSwitchApplication.PatientDetail s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.LabsCollection_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _LabsCollection_CreateQuery(global::LightSwitchApplication.PatientDetail.DetailsClass d, object[] args)
                {
                    return d.LabsCollectionQuery();
                }
                private static void _LabsCollection_SelectionChanged(global::LightSwitchApplication.PatientDetail s)
                {
                    s.LabsCollection_SelectionChanged();
                }
                private static void _LabsCollection_OnCollectionChanged(global::LightSwitchApplication.PatientDetail s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.LabsCollection_Changed(e);
                }
                private static void _LabsCollection_OnLoaded(global::LightSwitchApplication.PatientDetail s, bool succeeded)
                {
                    s.LabsCollection_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
    public sealed partial class SearchPatients
        : global::Microsoft.LightSwitch.Framework.Client.ScreenObject<global::LightSwitchApplication.SearchPatients, global::LightSwitchApplication.SearchPatients.DetailsClass>
    {
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private SearchPatients() : base("LightSwitchApplication:SearchPatients")
        {
            global::LightSwitchApplication.SearchPatients.DetailsClass.Initialize(this);
        }

        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public static SearchPatients CreateInstance()
        {
            return new global::LightSwitchApplication.SearchPatients(
            );
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPatients_InitializeDataWorkspace(global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPatients_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPatients_Activated();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPatients_Saving(ref bool handled);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPatients_Saved();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPatients_Closing(ref bool cancel);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SearchPatients_SaveError(global::System.Exception exception, ref bool handled);
     
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)((global::Microsoft.LightSwitch.Details.Client.IScreenDetails)this.Details).DataWorkspace;
            }
        }
        
        #endregion
 
        partial void Patients_SelectionChanged();

        partial void Patients_Changed(global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e);

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Loaded(bool succeeded);

        /// <summary>
        /// Gets the Patients visual collection. The collection contains all records currently shown on the respective list or grid control.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.Client.VisualCollection<global::LightSwitchApplication.Patient> Patients
        {
            get
            {
                return global::LightSwitchApplication.SearchPatients.DetailsClass.GetValue(this, global::LightSwitchApplication.SearchPatients.DetailsClass.PropertySetProperties.Patients);
            }
        }
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Validate(global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder results);
 
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass
            : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchPatients, global::LightSwitchApplication.SearchPatients.DetailsClass, global::LightSwitchApplication.SearchPatients.DetailsClass.PropertySet, global::LightSwitchApplication.SearchPatients.DetailsClass.CommandSet, global::LightSwitchApplication.SearchPatients.DetailsClass.MethodSet>
        {

            static DetailsClass()
            {
                var initializePropertyEntry = global::LightSwitchApplication.SearchPatients.DetailsClass.PropertySetProperties.Patients;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchPatients, global::LightSwitchApplication.SearchPatients.DetailsClass>.Entry
                __SearchPatientsEntry = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenDetails<global::LightSwitchApplication.SearchPatients, global::LightSwitchApplication.SearchPatients.DetailsClass>.Entry(
                    global::LightSwitchApplication.SearchPatients.DetailsClass.__SearchPatients_InvokeInitializeDataWorkspace,
                    global::LightSwitchApplication.SearchPatients.DetailsClass.__SearchPatients_InvokeSavingEvent,
                    global::LightSwitchApplication.SearchPatients.DetailsClass.__SearchPatients_InvokeSavedEvent,
                    global::LightSwitchApplication.SearchPatients.DetailsClass.__SearchPatients_InvokeClosingEvent,
                    global::LightSwitchApplication.SearchPatients.DetailsClass.__SearchPatients_InvokeCreated,
                    global::LightSwitchApplication.SearchPatients.DetailsClass.__SearchPatients_InvokeActivated,
                    global::LightSwitchApplication.SearchPatients.DetailsClass.__SearchPatients_InvokeSaveErrorEvent);
            private static void __SearchPatients_InvokeInitializeDataWorkspace(global::LightSwitchApplication.SearchPatients s, global::System.Collections.Generic.List<global::Microsoft.LightSwitch.IDataService> saveChangesTo)
            {
                s.SearchPatients_InitializeDataWorkspace(saveChangesTo);
            }
            private static bool __SearchPatients_InvokeSavingEvent(global::LightSwitchApplication.SearchPatients s)
            {
                bool handled = false;
                s.SearchPatients_Saving(ref handled);
                return handled;
            }
            private static void __SearchPatients_InvokeSavedEvent(global::LightSwitchApplication.SearchPatients s)
            {
                s.SearchPatients_Saved();
            }
            private static bool __SearchPatients_InvokeClosingEvent(global::LightSwitchApplication.SearchPatients s)
            {
                bool cancel = false;
                s.SearchPatients_Closing(ref cancel);
                return cancel;
            }
            private static void __SearchPatients_InvokeCreated(global::LightSwitchApplication.SearchPatients s)
            {
                s.SearchPatients_Created();
            }
            private static void __SearchPatients_InvokeActivated(global::LightSwitchApplication.SearchPatients s)
            {
                s.SearchPatients_Activated();
            }
            private static bool __SearchPatients_InvokeSaveErrorEvent(global::LightSwitchApplication.SearchPatients s, global::System.Exception ex)
            {
                bool handled = false;
                s.SearchPatients_SaveError(ex, ref handled);
                return handled;
            }

            public DetailsClass() : base()
            {
            }

            public new global::LightSwitchApplication.SearchPatients.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }

            public new global::LightSwitchApplication.SearchPatients.DetailsClass.CommandSet Commands
            {
                get
                {
                    return base.Commands;
                }
            }

            public new global::LightSwitchApplication.SearchPatients.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }

            private global::Microsoft.LightSwitch.IDataServiceQueryable PatientsQuery()
            {
                return this.Screen.DataWorkspace.ApplicationData.Patients;
            }

            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchPatients, global::LightSwitchApplication.SearchPatients.DetailsClass, global::LightSwitchApplication.Patient>.Data _Patients;

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenPropertySet<global::LightSwitchApplication.SearchPatients, global::LightSwitchApplication.SearchPatients.DetailsClass>
            {

                public global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchPatients, global::LightSwitchApplication.SearchPatients.DetailsClass, global::LightSwitchApplication.Patient> Patients
                {
                    get
                    {
                        return (global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchPatients, global::LightSwitchApplication.SearchPatients.DetailsClass, global::LightSwitchApplication.Patient>)base.GetItem(global::LightSwitchApplication.SearchPatients.DetailsClass.PropertySetProperties.Patients);
                    }
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class CommandSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCommandSet<global::LightSwitchApplication.SearchPatients, global::LightSwitchApplication.SearchPatients.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet
                : global::Microsoft.LightSwitch.Details.Framework.Client.ScreenMethodSet<global::LightSwitchApplication.SearchPatients, global::LightSwitchApplication.SearchPatients.DetailsClass>
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class PropertySetProperties
            {

                public static readonly global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchPatients, global::LightSwitchApplication.SearchPatients.DetailsClass, global::LightSwitchApplication.Patient>.Entry
                    Patients = new global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchPatients, global::LightSwitchApplication.SearchPatients.DetailsClass, global::LightSwitchApplication.Patient>.Entry(
                        "Patients",
                        global::LightSwitchApplication.SearchPatients.DetailsClass.PropertySetProperties._Patients_Stub,
                        global::LightSwitchApplication.SearchPatients.DetailsClass.PropertySetProperties._Patients_Validate,
                        global::LightSwitchApplication.SearchPatients.DetailsClass.PropertySetProperties._Patients_CreateQuery,
                        global::LightSwitchApplication.SearchPatients.DetailsClass.PropertySetProperties._Patients_SelectionChanged,
                        global::LightSwitchApplication.SearchPatients.DetailsClass.PropertySetProperties._Patients_OnCollectionChanged,
                        global::LightSwitchApplication.SearchPatients.DetailsClass.PropertySetProperties._Patients_OnLoaded);
                private static void _Patients_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.SearchPatients.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.Client.ScreenCollectionProperty<global::LightSwitchApplication.SearchPatients, global::LightSwitchApplication.SearchPatients.DetailsClass, global::LightSwitchApplication.Patient>.Data> c, global::LightSwitchApplication.SearchPatients.DetailsClass d, object sf)
                {
                    c(d, ref d._Patients, sf);
                }
                private static void _Patients_Validate(global::LightSwitchApplication.SearchPatients s, global::Microsoft.LightSwitch.Framework.Client.ScreenValidationResultsBuilder r)
                {
                    s.Patients_Validate(r);
                }
                private static global::Microsoft.LightSwitch.IDataServiceQueryable _Patients_CreateQuery(global::LightSwitchApplication.SearchPatients.DetailsClass d, object[] args)
                {
                    return d.PatientsQuery();
                }
                private static void _Patients_SelectionChanged(global::LightSwitchApplication.SearchPatients s)
                {
                    s.Patients_SelectionChanged();
                }
                private static void _Patients_OnCollectionChanged(global::LightSwitchApplication.SearchPatients s, global::System.Collections.Specialized.NotifyCollectionChangedEventArgs e)
                {
                    s.Patients_Changed(e);
                }
                private static void _Patients_OnLoaded(global::LightSwitchApplication.SearchPatients s, bool succeeded)
                {
                    s.Patients_Loaded(succeeded);
                }

            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class CommandSetProperties
            {
            }

            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal sealed class MethodSetProperties
            {
            }
        }
    }
}
