//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the ApplicationData datasource.
    /// </summary>
    public sealed partial class ApplicationDataService
        : global::LightSwitchApplication.ApplicationData
    {
        #region Constructors
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ApplicationDataService() : base()
        {
        }
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.Application Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "10.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Server Interceptions Points
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Inserting(global::LightSwitchApplication.Labs entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Inserted(global::LightSwitchApplication.Labs entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Updating(global::LightSwitchApplication.Labs entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Updated(global::LightSwitchApplication.Labs entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Deleting(global::LightSwitchApplication.Labs entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Deleted(global::LightSwitchApplication.Labs entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Validate(global::LightSwitchApplication.Labs entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_CanInsert(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_CanUpdate(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_CanDelete(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_CanRead(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Inserting(global::LightSwitchApplication.Patient entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Inserted(global::LightSwitchApplication.Patient entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Updating(global::LightSwitchApplication.Patient entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Updated(global::LightSwitchApplication.Patient entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Deleting(global::LightSwitchApplication.Patient entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Deleted(global::LightSwitchApplication.Patient entity);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Validate(global::LightSwitchApplication.Patient entity, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder results);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_Executed();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SaveChanges_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Single_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Single_Executing(global::System.Nullable<int> Id);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Single_PreprocessQuery(global::System.Nullable<int> Id, ref global::System.Linq.IQueryable<global::LightSwitchApplication.Labs> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Single_Executed(global::System.Nullable<int> Id, global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Labs> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_Single_ExecuteFailed(global::System.Nullable<int> Id, global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_SingleOrDefault_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_SingleOrDefault_Executing(global::System.Nullable<int> Id);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_SingleOrDefault_PreprocessQuery(global::System.Nullable<int> Id, ref global::System.Linq.IQueryable<global::LightSwitchApplication.Labs> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_SingleOrDefault_Executed(global::System.Nullable<int> Id, global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Labs> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_SingleOrDefault_ExecuteFailed(global::System.Nullable<int> Id, global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_All_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_All_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_All_PreprocessQuery(ref global::System.Linq.IQueryable<global::LightSwitchApplication.Labs> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_All_Executed(global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Labs> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LabsSet_All_ExecuteFailed(global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Single_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Single_Executing(global::System.Nullable<int> Id);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Single_PreprocessQuery(global::System.Nullable<int> Id, ref global::System.Linq.IQueryable<global::LightSwitchApplication.Patient> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Single_Executed(global::System.Nullable<int> Id, global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Patient> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_Single_ExecuteFailed(global::System.Nullable<int> Id, global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_SingleOrDefault_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_SingleOrDefault_Executing(global::System.Nullable<int> Id);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_SingleOrDefault_PreprocessQuery(global::System.Nullable<int> Id, ref global::System.Linq.IQueryable<global::LightSwitchApplication.Patient> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_SingleOrDefault_Executed(global::System.Nullable<int> Id, global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Patient> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_SingleOrDefault_ExecuteFailed(global::System.Nullable<int> Id, global::System.Exception exception);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_All_CanExecute(ref bool result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_All_Executing();
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_All_PreprocessQuery(ref global::System.Linq.IQueryable<global::LightSwitchApplication.Patient> query);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_All_Executed(global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Patient> result);
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Patients_All_ExecuteFailed(global::System.Exception exception);
    
        #endregion
    
        #region Details Class
    
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        public static new class DetailsClass
        {
    
            static DetailsClass()
            {
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Labs>
                __LabsSetEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Labs>(
                    "LabsSet",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_Validate);
            private static bool __LabsSet_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.LabsSet_CanInsert(ref result);
                return result;
            }
            private static bool __LabsSet_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.LabsSet_CanUpdate(ref result);
                return result;
            }
            private static bool __LabsSet_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.LabsSet_CanDelete(ref result);
                return result;
            }
            private static bool __LabsSet_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.LabsSet_CanRead(ref result);
                return result;
            }
            private static void __LabsSet_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Labs e)
            {
                d.LabsSet_Inserting(e);
            }
            private static void __LabsSet_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Labs e)
            {
                d.LabsSet_Inserted(e);
            }
            private static void __LabsSet_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Labs e)
            {
                d.LabsSet_Updating(e);
            }
            private static void __LabsSet_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Labs e)
            {
                d.LabsSet_Updated(e);
            }
            private static void __LabsSet_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Labs e)
            {
                d.LabsSet_Deleting(e);
            }
            private static void __LabsSet_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Labs e)
            {
                d.LabsSet_Deleted(e);
            }
            private static void __LabsSet_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Labs e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.LabsSet_Validate(e, r);
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Patient>
                __PatientsEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.EntitySetEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Patient>(
                    "Patients",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_CanInsert,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_CanUpdate,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_CanDelete,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_CanRead,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_Inserting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_Inserted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_Updating,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_Updated,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_Deleting,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_Deleted,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_Validate);
            private static bool __Patients_CanInsert(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Patients_CanInsert(ref result);
                return result;
            }
            private static bool __Patients_CanUpdate(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Patients_CanUpdate(ref result);
                return result;
            }
            private static bool __Patients_CanDelete(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Patients_CanDelete(ref result);
                return result;
            }
            private static bool __Patients_CanRead(global::LightSwitchApplication.ApplicationDataService d)
            {
                bool result = true;
                d.Patients_CanRead(ref result);
                return result;
            }
            private static void __Patients_Inserting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patient e)
            {
                d.Patients_Inserting(e);
            }
            private static void __Patients_Inserted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patient e)
            {
                d.Patients_Inserted(e);
            }
            private static void __Patients_Updating(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patient e)
            {
                d.Patients_Updating(e);
            }
            private static void __Patients_Updated(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patient e)
            {
                d.Patients_Updated(e);
            }
            private static void __Patients_Deleting(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patient e)
            {
                d.Patients_Deleting(e);
            }
            private static void __Patients_Deleted(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patient e)
            {
                d.Patients_Deleted(e);
            }
            private static void __Patients_Validate(global::LightSwitchApplication.ApplicationDataService d, global::LightSwitchApplication.Patient e, global::Microsoft.LightSwitch.EntitySetValidationResultsBuilder r)
            {
                d.Patients_Validate(e, r);
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>
                __SaveChangesEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.OperationEntry<global::LightSwitchApplication.ApplicationDataService>(
                    "SaveChanges",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__SaveChanges_Failed);
            private static bool __SaveChanges_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.SaveChanges_CanExecute(ref r);
                return r;
            }
            private static void __SaveChanges_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executing();
            }
            private static void __SaveChanges_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.SaveChanges_Executed();
            }
            private static void __SaveChanges_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.SaveChanges_ExecuteFailed(ex);
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Labs>
                __LabsSet_SingleEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Labs>(
                    "LabsSet_Single",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_Single_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_Single_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_Single_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_Single_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_Single_PreprocessQuery);
            private static bool __LabsSet_Single_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.LabsSet_Single_CanExecute(ref r);
                return r;
            }
            private static void __LabsSet_Single_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.LabsSet_Single_Executing((global::System.Nullable<int>)args[0]);
            }
            private static void __LabsSet_Single_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.LabsSet_Single_Executed((global::System.Nullable<int>)args[0], (global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Labs>)args[1]);
            }
            private static void __LabsSet_Single_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.LabsSet_Single_ExecuteFailed((global::System.Nullable<int>)args[0], ex);
            }
            private static global::System.Linq.IQueryable __LabsSet_Single_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.Labs> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.Labs>)args[1];
                d.LabsSet_Single_PreprocessQuery((global::System.Nullable<int>)args[0], ref query);
                return query;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Labs>
                __LabsSet_SingleOrDefaultEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Labs>(
                    "LabsSet_SingleOrDefault",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_SingleOrDefault_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_SingleOrDefault_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_SingleOrDefault_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_SingleOrDefault_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_SingleOrDefault_PreprocessQuery);
            private static bool __LabsSet_SingleOrDefault_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.LabsSet_SingleOrDefault_CanExecute(ref r);
                return r;
            }
            private static void __LabsSet_SingleOrDefault_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.LabsSet_SingleOrDefault_Executing((global::System.Nullable<int>)args[0]);
            }
            private static void __LabsSet_SingleOrDefault_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.LabsSet_SingleOrDefault_Executed((global::System.Nullable<int>)args[0], (global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Labs>)args[1]);
            }
            private static void __LabsSet_SingleOrDefault_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.LabsSet_SingleOrDefault_ExecuteFailed((global::System.Nullable<int>)args[0], ex);
            }
            private static global::System.Linq.IQueryable __LabsSet_SingleOrDefault_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.Labs> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.Labs>)args[1];
                d.LabsSet_SingleOrDefault_PreprocessQuery((global::System.Nullable<int>)args[0], ref query);
                return query;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Labs>
                __LabsSet_AllEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Labs>(
                    "LabsSet_All",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_All_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_All_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_All_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_All_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__LabsSet_All_PreprocessQuery);
            private static bool __LabsSet_All_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.LabsSet_All_CanExecute(ref r);
                return r;
            }
            private static void __LabsSet_All_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.LabsSet_All_Executing();
            }
            private static void __LabsSet_All_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.LabsSet_All_Executed((global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Labs>)args[0]);
            }
            private static void __LabsSet_All_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.LabsSet_All_ExecuteFailed(ex);
            }
            private static global::System.Linq.IQueryable __LabsSet_All_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.Labs> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.Labs>)args[0];
                d.LabsSet_All_PreprocessQuery(ref query);
                return query;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Patient>
                __Patients_SingleEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Patient>(
                    "Patients_Single",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_Single_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_Single_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_Single_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_Single_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_Single_PreprocessQuery);
            private static bool __Patients_Single_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.Patients_Single_CanExecute(ref r);
                return r;
            }
            private static void __Patients_Single_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.Patients_Single_Executing((global::System.Nullable<int>)args[0]);
            }
            private static void __Patients_Single_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.Patients_Single_Executed((global::System.Nullable<int>)args[0], (global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Patient>)args[1]);
            }
            private static void __Patients_Single_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.Patients_Single_ExecuteFailed((global::System.Nullable<int>)args[0], ex);
            }
            private static global::System.Linq.IQueryable __Patients_Single_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.Patient> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.Patient>)args[1];
                d.Patients_Single_PreprocessQuery((global::System.Nullable<int>)args[0], ref query);
                return query;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Patient>
                __Patients_SingleOrDefaultEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Patient>(
                    "Patients_SingleOrDefault",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_SingleOrDefault_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_SingleOrDefault_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_SingleOrDefault_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_SingleOrDefault_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_SingleOrDefault_PreprocessQuery);
            private static bool __Patients_SingleOrDefault_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.Patients_SingleOrDefault_CanExecute(ref r);
                return r;
            }
            private static void __Patients_SingleOrDefault_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.Patients_SingleOrDefault_Executing((global::System.Nullable<int>)args[0]);
            }
            private static void __Patients_SingleOrDefault_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.Patients_SingleOrDefault_Executed((global::System.Nullable<int>)args[0], (global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Patient>)args[1]);
            }
            private static void __Patients_SingleOrDefault_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.Patients_SingleOrDefault_ExecuteFailed((global::System.Nullable<int>)args[0], ex);
            }
            private static global::System.Linq.IQueryable __Patients_SingleOrDefault_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.Patient> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.Patient>)args[1];
                d.Patients_SingleOrDefault_PreprocessQuery((global::System.Nullable<int>)args[0], ref query);
                return query;
            }
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Patient>
                __Patients_AllEntry = new global::Microsoft.LightSwitch.Details.Framework.Server.QueryOperationEntry<global::LightSwitchApplication.ApplicationDataService, global::LightSwitchApplication.Patient>(
                    "Patients_All",
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_All_CanExecute,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_All_Executing,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_All_Executed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_All_Failed,
                    global::LightSwitchApplication.ApplicationDataService.DetailsClass.__Patients_All_PreprocessQuery);
            private static bool __Patients_All_CanExecute(global::LightSwitchApplication.ApplicationDataService d, bool r)
            {
                d.Patients_All_CanExecute(ref r);
                return r;
            }
            private static void __Patients_All_Executing(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.Patients_All_Executing();
            }
            private static void __Patients_All_Executed(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                d.Patients_All_Executed((global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Patient>)args[0]);
            }
            private static void __Patients_All_Failed(global::LightSwitchApplication.ApplicationDataService d, object[] args, global::System.Exception ex)
            {
                d.Patients_All_ExecuteFailed(ex);
            }
            private static global::System.Linq.IQueryable __Patients_All_PreprocessQuery(global::LightSwitchApplication.ApplicationDataService d, object[] args)
            {
                global::System.Linq.IQueryable<global::LightSwitchApplication.Patient> query = (global::System.Linq.IQueryable<global::LightSwitchApplication.Patient>)args[0];
                d.Patients_All_PreprocessQuery(ref query);
                return query;
            }
    
        }
    
        #endregion
    }
    
    #endregion
}
